package proyecto3poo;

import Mapa.*;
import Bloque.*;

public class Proyecto3POO {

    public static void main(String[] args) {
//        Bloque b = new Bloque(0,0,1,"imgs","grass",true,true);
//        Mapa mapa = new MapaBuilder()
//        .agregarBloque(b)
//        .agregarBloque(b)
//        .agregarBloque(b)
//        .build();
//        mapa.imprimir();


        BloqueFactory bFactory = new BloqueFactory();
        Bloque b = bFactory.createBloque("grass",0,1);
        System.out.println(""+b);
        // <editor-fold desc="Mapas builds">
       Mapa mapa1 = new MapaBuilder()
        .agregarBloque(bFactory.createBloque("brick", 2, 2))
        .agregarBloque(bFactory.createBloque("brick", 2, 3))
        .agregarBloque(bFactory.createBloque("brick", 2, 6))
        .agregarBloque(bFactory.createBloque("brick", 2, 7))
        .agregarBloque(bFactory.createBloque("brick", 2, 10))
        .agregarBloque(bFactory.createBloque("brick", 2, 11))
        .agregarBloque(bFactory.createBloque("brick", 2, 14))
        .agregarBloque(bFactory.createBloque("brick", 2, 15))
        .agregarBloque(bFactory.createBloque("brick", 2, 18))
        .agregarBloque(bFactory.createBloque("brick", 2, 19))
        .agregarBloque(bFactory.createBloque("brick", 2, 22))
        .agregarBloque(bFactory.createBloque("brick", 2, 23))

        .agregarBloque(bFactory.createBloque("brick", 3, 2))
        .agregarBloque(bFactory.createBloque("brick", 3, 3))
        .agregarBloque(bFactory.createBloque("brick", 3, 6))
        .agregarBloque(bFactory.createBloque("brick", 3, 7))
        .agregarBloque(bFactory.createBloque("brick", 3, 10))
        .agregarBloque(bFactory.createBloque("brick", 3, 11))
        .agregarBloque(bFactory.createBloque("brick", 3, 14))
        .agregarBloque(bFactory.createBloque("brick", 3, 15))
        .agregarBloque(bFactory.createBloque("brick", 3, 18))
        .agregarBloque(bFactory.createBloque("brick", 3, 19))
        .agregarBloque(bFactory.createBloque("brick", 3, 22))
        .agregarBloque(bFactory.createBloque("brick", 3, 23))
        .agregarBloque(bFactory.createBloque("brick", 4, 2))
        .agregarBloque(bFactory.createBloque("brick", 4, 3))
        .agregarBloque(bFactory.createBloque("brick", 4, 6))
        .agregarBloque(bFactory.createBloque("brick", 4, 7))
        .agregarBloque(bFactory.createBloque("brick", 4, 10))
        .agregarBloque(bFactory.createBloque("brick", 4, 11))
        .agregarBloque(bFactory.createBloque("brick", 4, 14))
        .agregarBloque(bFactory.createBloque("brick", 4, 15))
        .agregarBloque(bFactory.createBloque("brick", 4, 18))
        .agregarBloque(bFactory.createBloque("brick", 4, 19))
        .agregarBloque(bFactory.createBloque("brick", 4, 22))
        .agregarBloque(bFactory.createBloque("brick", 4, 23))

        .agregarBloque(bFactory.createBloque("brick", 5, 2))
        .agregarBloque(bFactory.createBloque("brick", 5, 3))
        .agregarBloque(bFactory.createBloque("brick", 5, 6))
        .agregarBloque(bFactory.createBloque("brick", 5, 7))
        .agregarBloque(bFactory.createBloque("brick", 5, 10))
        .agregarBloque(bFactory.createBloque("brick",5, 11))
        .agregarBloque(bFactory.createBloque("brick", 5, 14))
        .agregarBloque(bFactory.createBloque("brick", 5, 15))
        .agregarBloque(bFactory.createBloque("brick", 5, 18))
        .agregarBloque(bFactory.createBloque("brick",5 , 19))
        .agregarBloque(bFactory.createBloque("brick", 5, 22))
        .agregarBloque(bFactory.createBloque("brick",5 , 23))
        .agregarBloque(bFactory.createBloque("brick", 6, 2))
        .agregarBloque(bFactory.createBloque("brick",6 , 3))
        .agregarBloque(bFactory.createBloque("brick", 6, 6))
        .agregarBloque(bFactory.createBloque("brick",6 , 7))
        .agregarBloque(bFactory.createBloque("brick", 6, 10))
        .agregarBloque(bFactory.createBloque("brick",6 , 11))
        .agregarBloque(bFactory.createBloque("steel",6 , 12))
        .agregarBloque(bFactory.createBloque("steel",6 , 13))
        .agregarBloque(bFactory.createBloque("brick",6 , 14))
        .agregarBloque(bFactory.createBloque("brick", 6, 15))
        .agregarBloque(bFactory.createBloque("brick", 6, 18))
        .agregarBloque(bFactory.createBloque("brick",6 , 19))
        .agregarBloque(bFactory.createBloque("brick",6, 22))
        .agregarBloque(bFactory.createBloque("brick", 6, 23))

        .agregarBloque(bFactory.createBloque("brick", 7, 2))
        .agregarBloque(bFactory.createBloque("brick",7 , 3))
        .agregarBloque(bFactory.createBloque("brick",7 , 6))
        .agregarBloque(bFactory.createBloque("brick", 7, 7))
        .agregarBloque(bFactory.createBloque("brick", 7, 10))
        .agregarBloque(bFactory.createBloque("brick", 7, 11))
        .agregarBloque(bFactory.createBloque("steel",7 , 12))
        .agregarBloque(bFactory.createBloque("steel",7 , 13))
        .agregarBloque(bFactory.createBloque("brick", 7, 14))
        .agregarBloque(bFactory.createBloque("brick",7 , 15))
        .agregarBloque(bFactory.createBloque("brick", 7, 18))
        .agregarBloque(bFactory.createBloque("brick",7 , 19))
        .agregarBloque(bFactory.createBloque("brick", 7, 22))
        .agregarBloque(bFactory.createBloque("brick",7 , 23))
        .agregarBloque(bFactory.createBloque("brick",8 , 2))
        .agregarBloque(bFactory.createBloque("brick",8 , 3))
        .agregarBloque(bFactory.createBloque("brick",8 , 6))
        .agregarBloque(bFactory.createBloque("brick",8 , 7))
        .agregarBloque(bFactory.createBloque("brick",8 , 10))
        .agregarBloque(bFactory.createBloque("brick",8 , 11))
        .agregarBloque(bFactory.createBloque("brick", 8, 14))
        .agregarBloque(bFactory.createBloque("brick",8 , 15))
        .agregarBloque(bFactory.createBloque("brick",8 , 18))
        .agregarBloque(bFactory.createBloque("brick",8 , 19))
        .agregarBloque(bFactory.createBloque("brick",8 , 22))
        .agregarBloque(bFactory.createBloque("brick",8 , 23))

        .agregarBloque(bFactory.createBloque("brick",9 , 2))
        .agregarBloque(bFactory.createBloque("brick",9 , 3))
        .agregarBloque(bFactory.createBloque("brick", 9, 6))
        .agregarBloque(bFactory.createBloque("brick",9 , 7))
        .agregarBloque(bFactory.createBloque("brick",9 , 18))
        .agregarBloque(bFactory.createBloque("brick",9 , 19))
        .agregarBloque(bFactory.createBloque("brick",9 , 22))
        .agregarBloque(bFactory.createBloque("brick",9 , 23))

        .agregarBloque(bFactory.createBloque("brick",10 , 2))
        .agregarBloque(bFactory.createBloque("brick", 10, 3))
        .agregarBloque(bFactory.createBloque("brick", 10, 6))
        .agregarBloque(bFactory.createBloque("brick",10 , 7))
        .agregarBloque(bFactory.createBloque("brick", 10, 18))
        .agregarBloque(bFactory.createBloque("brick", 10, 19))
        .agregarBloque(bFactory.createBloque("brick", 10, 22))
        .agregarBloque(bFactory.createBloque("brick",10 , 23))
        .agregarBloque(bFactory.createBloque("brick",11 , 10))
        .agregarBloque(bFactory.createBloque("brick",11 , 11))
        .agregarBloque(bFactory.createBloque("brick",11 , 14))
        .agregarBloque(bFactory.createBloque("brick", 11, 15))

        .agregarBloque(bFactory.createBloque("brick",12 , 10))
        .agregarBloque(bFactory.createBloque("brick",12 , 11))
        .agregarBloque(bFactory.createBloque("brick",12 , 14))
        .agregarBloque(bFactory.createBloque("brick", 12, 15))

        .agregarBloque(bFactory.createBloque("brick",13 , 4))
        .agregarBloque(bFactory.createBloque("brick",13 , 5))
        .agregarBloque(bFactory.createBloque("brick",13 , 6))
        .agregarBloque(bFactory.createBloque("brick", 13, 7))
        .agregarBloque(bFactory.createBloque("brick",13 , 18))
        .agregarBloque(bFactory.createBloque("brick",13 , 19))
        .agregarBloque(bFactory.createBloque("brick",13 , 20))
        .agregarBloque(bFactory.createBloque("brick", 13, 21))
        .agregarBloque(bFactory.createBloque("steel",14 , 0))
        .agregarBloque(bFactory.createBloque("steel",14 , 1))
        .agregarBloque(bFactory.createBloque("brick",14 , 4))
        .agregarBloque(bFactory.createBloque("brick",14 , 5))
        .agregarBloque(bFactory.createBloque("brick",14 , 6))
        .agregarBloque(bFactory.createBloque("brick", 14, 7))
        .agregarBloque(bFactory.createBloque("brick",14 , 18))
        .agregarBloque(bFactory.createBloque("brick",14 , 19))
        .agregarBloque(bFactory.createBloque("brick",14 , 20))
        .agregarBloque(bFactory.createBloque("brick", 14, 21))
        .agregarBloque(bFactory.createBloque("steel",14 , 24))
        .agregarBloque(bFactory.createBloque("steel",14 , 25))

        .agregarBloque(bFactory.createBloque("brick",15 , 10))
        .agregarBloque(bFactory.createBloque("brick",15 , 11))
        .agregarBloque(bFactory.createBloque("brick",15 , 14))
        .agregarBloque(bFactory.createBloque("brick",15 , 15))


        .agregarBloque(bFactory.createBloque("brick",16 , 10))
        .agregarBloque(bFactory.createBloque("brick",16 , 11))
        .agregarBloque(bFactory.createBloque("brick",16 , 12))
        .agregarBloque(bFactory.createBloque("brick",16 , 13))
        .agregarBloque(bFactory.createBloque("brick",16 , 14))
        .agregarBloque(bFactory.createBloque("brick",16 , 15))
        .agregarBloque(bFactory.createBloque("brick",17 , 2))
        .agregarBloque(bFactory.createBloque("brick",17 , 3))
        .agregarBloque(bFactory.createBloque("brick",17 , 6))
        .agregarBloque(bFactory.createBloque("brick",17 , 7))
        .agregarBloque(bFactory.createBloque("brick",17 , 10))
        .agregarBloque(bFactory.createBloque("brick",17 , 11))
        .agregarBloque(bFactory.createBloque("brick",17 , 12))
        .agregarBloque(bFactory.createBloque("brick",17 , 13))
        .agregarBloque(bFactory.createBloque("brick",17 , 14))
        .agregarBloque(bFactory.createBloque("brick",17 , 15))
        .agregarBloque(bFactory.createBloque("brick",17 , 18))
        .agregarBloque(bFactory.createBloque("brick",17 , 19))
        .agregarBloque(bFactory.createBloque("brick",17 , 22))
        .agregarBloque(bFactory.createBloque("brick",17 , 23))

        .agregarBloque(bFactory.createBloque("brick", 18, 2))
        .agregarBloque(bFactory.createBloque("brick", 18, 3))
        .agregarBloque(bFactory.createBloque("brick", 18, 6))
        .agregarBloque(bFactory.createBloque("brick", 18, 7))
        .agregarBloque(bFactory.createBloque("brick", 18, 10))
        .agregarBloque(bFactory.createBloque("brick", 18, 11))
        .agregarBloque(bFactory.createBloque("brick", 18, 14))
        .agregarBloque(bFactory.createBloque("brick", 18, 15))
        .agregarBloque(bFactory.createBloque("brick", 18, 18))
        .agregarBloque(bFactory.createBloque("brick", 18, 19))
        .agregarBloque(bFactory.createBloque("brick", 18, 22))
        .agregarBloque(bFactory.createBloque("brick", 18, 23))
        .agregarBloque(bFactory.createBloque("brick", 19, 2))
        .agregarBloque(bFactory.createBloque("brick", 19, 3))
        .agregarBloque(bFactory.createBloque("brick", 19, 6))
        .agregarBloque(bFactory.createBloque("brick", 19, 7))
        .agregarBloque(bFactory.createBloque("brick", 19, 10))
        .agregarBloque(bFactory.createBloque("brick", 19, 11))
        .agregarBloque(bFactory.createBloque("brick", 19, 14))
        .agregarBloque(bFactory.createBloque("brick", 19, 15))
        .agregarBloque(bFactory.createBloque("brick", 19, 18))
        .agregarBloque(bFactory.createBloque("brick", 19, 19))
        .agregarBloque(bFactory.createBloque("brick", 19, 22))
        .agregarBloque(bFactory.createBloque("brick", 19, 23))

        .agregarBloque(bFactory.createBloque("brick", 20, 2))
        .agregarBloque(bFactory.createBloque("brick", 20, 3))
        .agregarBloque(bFactory.createBloque("brick", 20, 6))
        .agregarBloque(bFactory.createBloque("brick", 20, 7))
        .agregarBloque(bFactory.createBloque("brick", 20, 10))
        .agregarBloque(bFactory.createBloque("brick", 20, 11))
        .agregarBloque(bFactory.createBloque("brick", 20, 14))
        .agregarBloque(bFactory.createBloque("brick", 20, 15))
        .agregarBloque(bFactory.createBloque("brick", 20, 18))
        .agregarBloque(bFactory.createBloque("brick", 20, 19))
        .agregarBloque(bFactory.createBloque("brick", 20, 22))
        .agregarBloque(bFactory.createBloque("brick", 20, 23))
        .agregarBloque(bFactory.createBloque("brick", 21, 2))
        .agregarBloque(bFactory.createBloque("brick", 21, 3))
        .agregarBloque(bFactory.createBloque("brick", 21, 6))
        .agregarBloque(bFactory.createBloque("brick", 21, 7))
        .agregarBloque(bFactory.createBloque("brick", 21, 18))
        .agregarBloque(bFactory.createBloque("brick", 21, 19))
        .agregarBloque(bFactory.createBloque("brick", 21, 22))
        .agregarBloque(bFactory.createBloque("brick", 21, 23))

        .agregarBloque(bFactory.createBloque("brick", 22, 2))
        .agregarBloque(bFactory.createBloque("brick", 22, 3))
        .agregarBloque(bFactory.createBloque("brick", 22, 6))
        .agregarBloque(bFactory.createBloque("brick", 22, 7))
        .agregarBloque(bFactory.createBloque("brick", 22, 18))
        .agregarBloque(bFactory.createBloque("brick", 22, 19))
        .agregarBloque(bFactory.createBloque("brick", 22, 22))
        .agregarBloque(bFactory.createBloque("brick", 22, 23))
        .agregarBloque(bFactory.createBloque("brick", 23, 2))
        .agregarBloque(bFactory.createBloque("brick", 23, 3))
        .agregarBloque(bFactory.createBloque("brick", 23, 6))
        .agregarBloque(bFactory.createBloque("brick", 23, 7))
        .agregarBloque(bFactory.createBloque("brick", 23, 11))
        .agregarBloque(bFactory.createBloque("brick", 23, 12))
        .agregarBloque(bFactory.createBloque("brick", 23, 13))
        .agregarBloque(bFactory.createBloque("brick", 23, 14))
        .agregarBloque(bFactory.createBloque("brick", 23, 18))
        .agregarBloque(bFactory.createBloque("brick", 23, 19))
        .agregarBloque(bFactory.createBloque("brick", 23, 22))
        .agregarBloque(bFactory.createBloque("brick", 23, 23))


        .agregarBloque(bFactory.createBloque("brick", 24, 11))
        .agregarBloque(bFactory.createBloque("brick", 24, 14))
        .agregarBloque(bFactory.createBloque("brick", 25, 11))
        .agregarBloque(bFactory.createBloque("brick", 25, 14))
        .build();
       filemanager.FileManager.writeObject(mapa1, "Mapas\\mapa1.txt");

       
       
       
       
       
        Mapa mapa2 = new MapaBuilder()
        .agregarBloque(bFactory.createBloque("steel", 0, 6))
        .agregarBloque(bFactory.createBloque("steel", 0, 7))
        .agregarBloque(bFactory.createBloque("steel", 0, 14))
        .agregarBloque(bFactory.createBloque("steel", 0, 15))

        .agregarBloque(bFactory.createBloque("steel", 1, 6))
        .agregarBloque(bFactory.createBloque("steel", 1, 7))
        .agregarBloque(bFactory.createBloque("steel", 1, 14))
        .agregarBloque(bFactory.createBloque("steel", 1, 15))
        
        .agregarBloque(bFactory.createBloque("brick", 2, 2))
        .agregarBloque(bFactory.createBloque("brick", 2, 3))
        .agregarBloque(bFactory.createBloque("steel", 2, 6))
        .agregarBloque(bFactory.createBloque("steel", 2, 7))
        .agregarBloque(bFactory.createBloque("brick", 2, 14))
        .agregarBloque(bFactory.createBloque("brick", 2, 15))
        .agregarBloque(bFactory.createBloque("brick", 2, 18))
        .agregarBloque(bFactory.createBloque("brick", 2, 19))
        .agregarBloque(bFactory.createBloque("brick", 2, 22))
        .agregarBloque(bFactory.createBloque("brick", 2, 23))
        

        .agregarBloque(bFactory.createBloque("brick", 3, 2))
        .agregarBloque(bFactory.createBloque("brick", 3, 3))
        .agregarBloque(bFactory.createBloque("steel", 3, 6))
        .agregarBloque(bFactory.createBloque("steel", 3, 7))
        .agregarBloque(bFactory.createBloque("brick", 3, 14))
        .agregarBloque(bFactory.createBloque("brick", 3, 15))
        .agregarBloque(bFactory.createBloque("brick", 3, 18))
        .agregarBloque(bFactory.createBloque("brick", 3, 19))
        .agregarBloque(bFactory.createBloque("brick", 3, 22))
        .agregarBloque(bFactory.createBloque("brick", 3, 23))

        .agregarBloque(bFactory.createBloque("brick", 4, 2))
        .agregarBloque(bFactory.createBloque("brick",4, 3))
        .agregarBloque(bFactory.createBloque("brick", 4, 14))
        .agregarBloque(bFactory.createBloque("brick",4 , 15))
        .agregarBloque(bFactory.createBloque("brick", 4, 18))
        .agregarBloque(bFactory.createBloque("brick",4 , 19))
        .agregarBloque(bFactory.createBloque("steel",4 , 20))
        .agregarBloque(bFactory.createBloque("steel",4 , 21))
        .agregarBloque(bFactory.createBloque("brick",4 , 22))
        .agregarBloque(bFactory.createBloque("brick", 4, 23))
        

        .agregarBloque(bFactory.createBloque("brick", 5, 2))
        .agregarBloque(bFactory.createBloque("brick",5, 3))
        .agregarBloque(bFactory.createBloque("brick", 5, 12))
        .agregarBloque(bFactory.createBloque("brick",5, 13))
        .agregarBloque(bFactory.createBloque("brick", 5, 14))
        .agregarBloque(bFactory.createBloque("brick",5 , 15))
        .agregarBloque(bFactory.createBloque("brick", 5, 18))
        .agregarBloque(bFactory.createBloque("brick",5 , 19))
        .agregarBloque(bFactory.createBloque("steel",5 , 20))
        .agregarBloque(bFactory.createBloque("steel",5 , 21))
        .agregarBloque(bFactory.createBloque("brick",5 , 22))
        .agregarBloque(bFactory.createBloque("brick", 5,23))

        .agregarBloque(bFactory.createBloque("brick",6 , 6))
        .agregarBloque(bFactory.createBloque("brick",6 , 7))
        .agregarBloque(bFactory.createBloque("steel",6 , 18))
        .agregarBloque(bFactory.createBloque("steel",6, 19))
                
                
        .agregarBloque(bFactory.createBloque("brick",7 , 6))
        .agregarBloque(bFactory.createBloque("brick",7  , 7))
        .agregarBloque(bFactory.createBloque("steel",7  , 18))
        .agregarBloque(bFactory.createBloque("steel",7 , 19))
        
        .agregarBloque(bFactory.createBloque("grass",8 , 0))
        .agregarBloque(bFactory.createBloque("grass",8  , 1))
        .agregarBloque(bFactory.createBloque("brick",8  , 6))
        .agregarBloque(bFactory.createBloque("brick",8 , 7))
        .agregarBloque(bFactory.createBloque("steel",8  , 12))
        .agregarBloque(bFactory.createBloque("steel",8 , 13))
        .agregarBloque(bFactory.createBloque("brick",8  , 18))
        .agregarBloque(bFactory.createBloque("brick",8 , 19))
        .agregarBloque(bFactory.createBloque("grass",8 , 20))
        .agregarBloque(bFactory.createBloque("grass",8  , 21))      
        .agregarBloque(bFactory.createBloque("brick",8  , 22))
        .agregarBloque(bFactory.createBloque("brick",8 , 23))
        .agregarBloque(bFactory.createBloque("steel",8  , 24))
        .agregarBloque(bFactory.createBloque("steel",8 , 25))
                
        .agregarBloque(bFactory.createBloque("grass",9 , 0))
        .agregarBloque(bFactory.createBloque("grass",9  , 1))
        .agregarBloque(bFactory.createBloque("brick",9  , 6))
        .agregarBloque(bFactory.createBloque("brick",9 , 7))
        .agregarBloque(bFactory.createBloque("steel",9  , 12))
        .agregarBloque(bFactory.createBloque("steel",9 , 13))
        .agregarBloque(bFactory.createBloque("brick",9  , 18))
        .agregarBloque(bFactory.createBloque("brick",9 , 19))
        .agregarBloque(bFactory.createBloque("grass",9 , 20))
        .agregarBloque(bFactory.createBloque("grass",9  , 21))      
        .agregarBloque(bFactory.createBloque("brick",9  , 22))
        .agregarBloque(bFactory.createBloque("brick",9 , 23))
        .agregarBloque(bFactory.createBloque("steel",9  , 24))
        .agregarBloque(bFactory.createBloque("steel",9 , 25))
        
        .agregarBloque(bFactory.createBloque("grass", 10, 0))
	.agregarBloque(bFactory.createBloque("grass", 10, 1))
	.agregarBloque(bFactory.createBloque("grass",10 , 2))
	.agregarBloque(bFactory.createBloque("grass", 10, 3))
	.agregarBloque(bFactory.createBloque("brick", 10, 10))
	.agregarBloque(bFactory.createBloque("brick", 10, 11))
	.agregarBloque(bFactory.createBloque("steel", 10, 16))
	.agregarBloque(bFactory.createBloque("steel", 10, 17))  
        .agregarBloque(bFactory.createBloque("grass", 10, 20))
	.agregarBloque(bFactory.createBloque("grass", 10, 21)) 
                
        .agregarBloque(bFactory.createBloque("grass", 11, 0))
	.agregarBloque(bFactory.createBloque("grass", 11, 1))
	.agregarBloque(bFactory.createBloque("grass",11 , 2))
	.agregarBloque(bFactory.createBloque("grass", 11, 3))
	.agregarBloque(bFactory.createBloque("brick", 11, 10))
	.agregarBloque(bFactory.createBloque("brick", 11, 11))
	.agregarBloque(bFactory.createBloque("steel", 11, 16))
	.agregarBloque(bFactory.createBloque("steel", 11, 17))  
        .agregarBloque(bFactory.createBloque("grass", 11, 20))
	.agregarBloque(bFactory.createBloque("grass", 11, 21))
        
        .agregarBloque(bFactory.createBloque("brick", 12, 2))
	.agregarBloque(bFactory.createBloque("brick",12, 3))
	.agregarBloque(bFactory.createBloque("brick",12 , 4))
	.agregarBloque(bFactory.createBloque("brick",12 , 5))
	.agregarBloque(bFactory.createBloque("brick",12 , 6))
	.agregarBloque(bFactory.createBloque("brick", 12, 7))
	.agregarBloque(bFactory.createBloque("grass",12 , 8))
	.agregarBloque(bFactory.createBloque("grass",12 , 9))
        .agregarBloque(bFactory.createBloque("grass",12 , 10))
	.agregarBloque(bFactory.createBloque("grass",12 , 11)) 
        .agregarBloque(bFactory.createBloque("grass",12 , 12))
	.agregarBloque(bFactory.createBloque("grass",12 , 13))
        .agregarBloque(bFactory.createBloque("steel",12 , 14))
	.agregarBloque(bFactory.createBloque("steel",12 , 15)) 
        .agregarBloque(bFactory.createBloque("grass",12 , 20))
	.agregarBloque(bFactory.createBloque("grass",12 , 21))
        .agregarBloque(bFactory.createBloque("brick",12 , 22))
	.agregarBloque(bFactory.createBloque("brick", 12, 23))
                
        .agregarBloque(bFactory.createBloque("brick", 13, 2))
	.agregarBloque(bFactory.createBloque("brick",13, 3))
	.agregarBloque(bFactory.createBloque("brick",13 , 4))
	.agregarBloque(bFactory.createBloque("brick",13 , 5))
	.agregarBloque(bFactory.createBloque("brick",13 , 6))
	.agregarBloque(bFactory.createBloque("brick", 13, 7))
	.agregarBloque(bFactory.createBloque("grass",13 , 8))
	.agregarBloque(bFactory.createBloque("grass",13 , 9))
        .agregarBloque(bFactory.createBloque("grass",13 , 10))
	.agregarBloque(bFactory.createBloque("grass",13 , 11)) 
        .agregarBloque(bFactory.createBloque("grass",13 , 12))
	.agregarBloque(bFactory.createBloque("grass",13 , 13))
        .agregarBloque(bFactory.createBloque("steel",13 , 14))
	.agregarBloque(bFactory.createBloque("steel",13 , 15)) 
        .agregarBloque(bFactory.createBloque("grass",13 , 20))
	.agregarBloque(bFactory.createBloque("grass",13 , 21))
        .agregarBloque(bFactory.createBloque("brick",13 , 22))
	.agregarBloque(bFactory.createBloque("brick", 13, 23))
                
        .agregarBloque(bFactory.createBloque("steel", 14, 6))
	.agregarBloque(bFactory.createBloque("steel", 14, 7))
	.agregarBloque(bFactory.createBloque("grass", 14, 8))
	.agregarBloque(bFactory.createBloque("grass", 14, 9))
	.agregarBloque(bFactory.createBloque("brick", 14, 10))
	.agregarBloque(bFactory.createBloque("brick",14 , 11))
	.agregarBloque(bFactory.createBloque("brick", 14, 14))    
        .agregarBloque(bFactory.createBloque("brick",14 , 15))
	.agregarBloque(bFactory.createBloque("brick",14 , 18))
	.agregarBloque(bFactory.createBloque("brick",14 , 19))
	.agregarBloque(bFactory.createBloque("brick",14 , 22))
	.agregarBloque(bFactory.createBloque("brick",14 , 23))
           
        .agregarBloque(bFactory.createBloque("steel", 15, 6))
	.agregarBloque(bFactory.createBloque("steel", 15, 7))
	.agregarBloque(bFactory.createBloque("grass", 15, 8))
	.agregarBloque(bFactory.createBloque("grass", 15, 9))
	.agregarBloque(bFactory.createBloque("brick", 15, 10))
	.agregarBloque(bFactory.createBloque("brick",15 , 11))
	.agregarBloque(bFactory.createBloque("brick", 15, 14))    
        .agregarBloque(bFactory.createBloque("brick",15 , 15))
	.agregarBloque(bFactory.createBloque("brick",15 , 18))
	.agregarBloque(bFactory.createBloque("brick",15 , 19))
	.agregarBloque(bFactory.createBloque("brick",15 , 22))
	.agregarBloque(bFactory.createBloque("brick",15 , 23))     
        
                
        .agregarBloque(bFactory.createBloque("steel",16 , 0))
	.agregarBloque(bFactory.createBloque("steel", 16, 1))
	.agregarBloque(bFactory.createBloque("brick", 16, 2))
	.agregarBloque(bFactory.createBloque("brick", 16, 3))
	.agregarBloque(bFactory.createBloque("steel", 16, 6))
	.agregarBloque(bFactory.createBloque("steel", 16, 7))
	.agregarBloque(bFactory.createBloque("brick",16 , 10))
	.agregarBloque(bFactory.createBloque("brick",16 ,11))
        .agregarBloque(bFactory.createBloque("brick",16 , 14))
	.agregarBloque(bFactory.createBloque("brick",16 , 15))
	.agregarBloque(bFactory.createBloque("brick",16 , 22))
	.agregarBloque(bFactory.createBloque("brick",16 , 23))
                
        .agregarBloque(bFactory.createBloque("steel",17 , 0))
	.agregarBloque(bFactory.createBloque("steel", 17, 1))
	.agregarBloque(bFactory.createBloque("brick", 17, 2))
	.agregarBloque(bFactory.createBloque("brick", 17, 3))
	.agregarBloque(bFactory.createBloque("steel", 17, 6))
	.agregarBloque(bFactory.createBloque("steel", 17, 7))
	.agregarBloque(bFactory.createBloque("brick",17 , 10))
	.agregarBloque(bFactory.createBloque("brick",17 ,11))
        .agregarBloque(bFactory.createBloque("brick",17 , 14))
	.agregarBloque(bFactory.createBloque("brick",17 , 15))
	.agregarBloque(bFactory.createBloque("brick",17 , 22))
	.agregarBloque(bFactory.createBloque("brick",17 , 23))
             
        .agregarBloque(bFactory.createBloque("brick",18 , 2))
	.agregarBloque(bFactory.createBloque("brick", 18, 3))
	.agregarBloque(bFactory.createBloque("brick", 18, 6))
	.agregarBloque(bFactory.createBloque("brick",18 , 7))
	.agregarBloque(bFactory.createBloque("brick",18 , 10))
	.agregarBloque(bFactory.createBloque("brick", 18, 11))
	.agregarBloque(bFactory.createBloque("brick", 18, 12))
	.agregarBloque(bFactory.createBloque("brick", 18, 13))
        .agregarBloque(bFactory.createBloque("brick",18 , 14))
	.agregarBloque(bFactory.createBloque("brick", 18, 15))
	.agregarBloque(bFactory.createBloque("brick", 18, 18))
	.agregarBloque(bFactory.createBloque("brick",18 , 19))
	.agregarBloque(bFactory.createBloque("steel",18 , 20))
	.agregarBloque(bFactory.createBloque("steel", 18, 21))
	.agregarBloque(bFactory.createBloque("brick", 18, 22))
	.agregarBloque(bFactory.createBloque("brick", 18,  23))
                
        .agregarBloque(bFactory.createBloque("brick",19 , 2))
	.agregarBloque(bFactory.createBloque("brick", 19, 3))
	.agregarBloque(bFactory.createBloque("brick", 19, 6))
	.agregarBloque(bFactory.createBloque("brick",19 , 7))
	.agregarBloque(bFactory.createBloque("brick",19 , 10))
	.agregarBloque(bFactory.createBloque("brick", 19, 11))
	.agregarBloque(bFactory.createBloque("brick", 19, 12))
	.agregarBloque(bFactory.createBloque("brick", 19, 13))
        .agregarBloque(bFactory.createBloque("brick",19 , 14))
	.agregarBloque(bFactory.createBloque("brick", 19, 15))
	.agregarBloque(bFactory.createBloque("brick", 19, 18))
	.agregarBloque(bFactory.createBloque("brick",19 , 19))
	.agregarBloque(bFactory.createBloque("steel",19 , 20))
	.agregarBloque(bFactory.createBloque("steel", 19, 21))
	.agregarBloque(bFactory.createBloque("brick", 19, 22))
	.agregarBloque(bFactory.createBloque("brick", 19,  23))
                
        .agregarBloque(bFactory.createBloque("brick",20 , 2))
	.agregarBloque(bFactory.createBloque("brick", 20, 3))
	.agregarBloque(bFactory.createBloque("brick", 20, 6))
	.agregarBloque(bFactory.createBloque("brick",20 , 7))
	.agregarBloque(bFactory.createBloque("brick",20 , 10))
	.agregarBloque(bFactory.createBloque("brick", 20, 11))
	.agregarBloque(bFactory.createBloque("brick", 20, 12))
	.agregarBloque(bFactory.createBloque("brick", 20, 13))
        .agregarBloque(bFactory.createBloque("brick",20 , 14))
	.agregarBloque(bFactory.createBloque("brick", 20, 15))
                
                
        .agregarBloque(bFactory.createBloque("brick",21 , 2))
	.agregarBloque(bFactory.createBloque("brick", 21, 3))
	.agregarBloque(bFactory.createBloque("brick", 21, 6))
	.agregarBloque(bFactory.createBloque("brick",21 , 7))
	.agregarBloque(bFactory.createBloque("brick",21 , 10))
	.agregarBloque(bFactory.createBloque("brick", 21, 11))
	.agregarBloque(bFactory.createBloque("brick", 21, 12))
	.agregarBloque(bFactory.createBloque("brick", 21, 13))
        .agregarBloque(bFactory.createBloque("brick",21 , 14))
	.agregarBloque(bFactory.createBloque("brick", 21, 15))
                
        .agregarBloque(bFactory.createBloque("brick",22 , 2))
	.agregarBloque(bFactory.createBloque("brick", 22, 3))
	.agregarBloque(bFactory.createBloque("brick", 22, 18))
	.agregarBloque(bFactory.createBloque("brick",22 , 19))
	.agregarBloque(bFactory.createBloque("brick",22 , 22))
	.agregarBloque(bFactory.createBloque("brick", 22, 23))
                
                
                
	.agregarBloque(bFactory.createBloque("brick", 23, 2))
	.agregarBloque(bFactory.createBloque("brick", 23, 3))
        .agregarBloque(bFactory.createBloque("brick",23 , 11))
	.agregarBloque(bFactory.createBloque("brick", 23, 12))
        .agregarBloque(bFactory.createBloque("brick",23 , 13))
	.agregarBloque(bFactory.createBloque("brick", 23, 14))
	.agregarBloque(bFactory.createBloque("brick", 23, 18))
	.agregarBloque(bFactory.createBloque("brick",23 , 19))
	.agregarBloque(bFactory.createBloque("brick",23 , 22))
	.agregarBloque(bFactory.createBloque("brick", 23, 23))
	
                
                
        .agregarBloque(bFactory.createBloque("brick", 24, 2))
	.agregarBloque(bFactory.createBloque("brick", 24,3))
        .agregarBloque(bFactory.createBloque("brick",24 , 6))
	.agregarBloque(bFactory.createBloque("brick", 24, 7))
        .agregarBloque(bFactory.createBloque("brick", 24, 11))
	.agregarBloque(bFactory.createBloque("brick", 24, 14))
        .agregarBloque(bFactory.createBloque("brick",24 , 18))
	.agregarBloque(bFactory.createBloque("brick", 24, 19))
        .agregarBloque(bFactory.createBloque("brick", 24, 20))
        .agregarBloque(bFactory.createBloque("brick", 24, 21))
	.agregarBloque(bFactory.createBloque("brick", 24, 22))
        .agregarBloque(bFactory.createBloque("brick",24 , 23))
                
        .agregarBloque(bFactory.createBloque("brick", 25, 2))
	.agregarBloque(bFactory.createBloque("brick", 25,3))
        .agregarBloque(bFactory.createBloque("brick",25 , 6))
	.agregarBloque(bFactory.createBloque("brick", 25, 7))
        .agregarBloque(bFactory.createBloque("brick", 25, 11))
	.agregarBloque(bFactory.createBloque("brick", 25, 14))
        .agregarBloque(bFactory.createBloque("brick",25 , 18))
	.agregarBloque(bFactory.createBloque("brick", 25, 19))
        .agregarBloque(bFactory.createBloque("brick", 25, 20))
        .agregarBloque(bFactory.createBloque("brick", 25, 21))
	.agregarBloque(bFactory.createBloque("brick", 25, 22))
        .agregarBloque(bFactory.createBloque("brick",25 , 23))
        .build();
        filemanager.FileManager.writeObject(mapa2, "Mapas\\mapa2.txt");
        
        
        
        
        Mapa mapa3 = new MapaBuilder()
        .agregarBloque(bFactory.createBloque("steel", 0, 10))
        .agregarBloque(bFactory.createBloque("steel", 0, 11))
        .agregarBloque(bFactory.createBloque("brick", 0, 14))
        .agregarBloque(bFactory.createBloque("brick", 0, 15))
        .agregarBloque(bFactory.createBloque("brick", 0, 18))
        .agregarBloque(bFactory.createBloque("brick", 0, 19))
        .agregarBloque(bFactory.createBloque("brick", 0, 20))
        .agregarBloque(bFactory.createBloque("brick", 0, 21))

        .agregarBloque(bFactory.createBloque("steel", 1, 10))
        .agregarBloque(bFactory.createBloque("steel", 1,11))
        .agregarBloque(bFactory.createBloque("brick", 1,14))
        .agregarBloque(bFactory.createBloque("brick", 1, 15))
        .agregarBloque(bFactory.createBloque("brick", 1, 18))
        .agregarBloque(bFactory.createBloque("brick", 1, 19))
        .agregarBloque(bFactory.createBloque("brick", 1, 20))
        .agregarBloque(bFactory.createBloque("brick", 1, 21))
        
        .agregarBloque(bFactory.createBloque("brick", 2, 2))
        .agregarBloque(bFactory.createBloque("brick", 2, 3))
        .agregarBloque(bFactory.createBloque("brick", 2, 4))
        .agregarBloque(bFactory.createBloque("brick", 2, 5))
        .agregarBloque(bFactory.createBloque("brick", 2, 6))
        .agregarBloque(bFactory.createBloque("brick", 2, 7))
        .agregarBloque(bFactory.createBloque("brick", 2, 8))
        .agregarBloque(bFactory.createBloque("brick", 2, 9))
        .agregarBloque(bFactory.createBloque("brick", 2, 10))
        .agregarBloque(bFactory.createBloque("brick", 2, 11))
        .agregarBloque(bFactory.createBloque("brick", 2, 14))
        .agregarBloque(bFactory.createBloque("brick", 2, 15))

        .agregarBloque(bFactory.createBloque("brick", 3, 2))
        .agregarBloque(bFactory.createBloque("brick", 3, 3))
        .agregarBloque(bFactory.createBloque("brick", 3,4))
        .agregarBloque(bFactory.createBloque("brick", 3, 5))
        .agregarBloque(bFactory.createBloque("brick", 3, 6))
        .agregarBloque(bFactory.createBloque("brick", 3, 7))
        .agregarBloque(bFactory.createBloque("brick", 3, 8))
        .agregarBloque(bFactory.createBloque("brick", 3, 9))
        .agregarBloque(bFactory.createBloque("brick", 3, 10))
        .agregarBloque(bFactory.createBloque("brick", 3, 11))
        .agregarBloque(bFactory.createBloque("brick", 3, 14))
        .agregarBloque(bFactory.createBloque("brick", 3, 15))

        .agregarBloque(bFactory.createBloque("brick", 4, 6))
        .agregarBloque(bFactory.createBloque("brick",4, 10))
        .agregarBloque(bFactory.createBloque("brick", 4, 11))
        .agregarBloque(bFactory.createBloque("brick",4 , 14))
        .agregarBloque(bFactory.createBloque("brick", 4, 15))
        .agregarBloque(bFactory.createBloque("brick",4 , 16))
        .agregarBloque(bFactory.createBloque("brick",4 , 17))
        .agregarBloque(bFactory.createBloque("grass",4 , 20))
        .agregarBloque(bFactory.createBloque("grass",4 , 21))
        .agregarBloque(bFactory.createBloque("grass", 4, 22))
        .agregarBloque(bFactory.createBloque("grass",4 , 23))
        .agregarBloque(bFactory.createBloque("grass", 4, 24))
        .agregarBloque(bFactory.createBloque("grass", 4, 25))
        

        .agregarBloque(bFactory.createBloque("brick", 5, 6))
        .agregarBloque(bFactory.createBloque("brick",5, 10))
        .agregarBloque(bFactory.createBloque("brick", 5, 11))
        .agregarBloque(bFactory.createBloque("brick",5 , 14))
        .agregarBloque(bFactory.createBloque("brick", 5, 15))
        .agregarBloque(bFactory.createBloque("brick",5 , 16))
        .agregarBloque(bFactory.createBloque("brick",5 , 17))
        .agregarBloque(bFactory.createBloque("grass",5 , 20))
        .agregarBloque(bFactory.createBloque("grass",5 , 21))
        .agregarBloque(bFactory.createBloque("grass", 5, 22))
        .agregarBloque(bFactory.createBloque("grass",5 , 23))
        .agregarBloque(bFactory.createBloque("grass", 5, 24))
        .agregarBloque(bFactory.createBloque("grass", 5, 25))

        .agregarBloque(bFactory.createBloque("brick",6 , 3))
        .agregarBloque(bFactory.createBloque("steel",6 , 14))
        .agregarBloque(bFactory.createBloque("steel",6 , 15))
        .agregarBloque(bFactory.createBloque("grass",6, 18))
        .agregarBloque(bFactory.createBloque("grass",6 , 19))
        .agregarBloque(bFactory.createBloque("grass",6 , 20))
        .agregarBloque(bFactory.createBloque("grass",6 , 21))
        .agregarBloque(bFactory.createBloque("grass",6, 22))
        .agregarBloque(bFactory.createBloque("grass",6 , 23))
        .agregarBloque(bFactory.createBloque("grass",6 , 24))
        .agregarBloque(bFactory.createBloque("grass",6 , 25))  
                
        .agregarBloque(bFactory.createBloque("brick",7 , 3))
        .agregarBloque(bFactory.createBloque("steel",7  , 14))
        .agregarBloque(bFactory.createBloque("steel",7 , 15))
        .agregarBloque(bFactory.createBloque("grass",7 , 18))
        .agregarBloque(bFactory.createBloque("grass",7  , 19))
        .agregarBloque(bFactory.createBloque("grass",7  , 20))
        .agregarBloque(bFactory.createBloque("grass",7  , 21))
        .agregarBloque(bFactory.createBloque("grass",7 , 22))
        .agregarBloque(bFactory.createBloque("grass",7  , 23))
        .agregarBloque(bFactory.createBloque("grass",7  , 24))
        .agregarBloque(bFactory.createBloque("grass",7  , 25)) 
        
        .agregarBloque(bFactory.createBloque("brick",8 , 3))
        .agregarBloque(bFactory.createBloque("brick",8  , 6))
        .agregarBloque(bFactory.createBloque("brick",8  , 7))
        .agregarBloque(bFactory.createBloque("brick",8 , 8))
        .agregarBloque(bFactory.createBloque("brick",8  , 9))
        .agregarBloque(bFactory.createBloque("brick",8 , 10))
        .agregarBloque(bFactory.createBloque("brick",8  , 11))
        .agregarBloque(bFactory.createBloque("steel",8 , 12))
        .agregarBloque(bFactory.createBloque("steel",8 , 13))
        .agregarBloque(bFactory.createBloque("brick",8  , 14))      
        .agregarBloque(bFactory.createBloque("brick",8  , 15))
        .agregarBloque(bFactory.createBloque("brick",8 , 16))
        .agregarBloque(bFactory.createBloque("brick",8  , 17))
        .agregarBloque(bFactory.createBloque("grass",8 ,18 ))
        .agregarBloque(bFactory.createBloque("grass",8 , 19))
        .agregarBloque(bFactory.createBloque("grass",8  , 20))
        .agregarBloque(bFactory.createBloque("grass",8 , 21))
        .agregarBloque(bFactory.createBloque("brick",8 , 22))
        .agregarBloque(bFactory.createBloque("brick",8  , 23))      
        .agregarBloque(bFactory.createBloque("steel",8  , 24))
        .agregarBloque(bFactory.createBloque("steel",8 , 25))
                
        .agregarBloque(bFactory.createBloque("brick",9 , 3))
        .agregarBloque(bFactory.createBloque("brick",9  , 6))
        .agregarBloque(bFactory.createBloque("brick",9  , 7))
        .agregarBloque(bFactory.createBloque("brick",9 , 8))
        .agregarBloque(bFactory.createBloque("brick",9  , 9))
        .agregarBloque(bFactory.createBloque("brick",9 , 10))
        .agregarBloque(bFactory.createBloque("brick",9  , 11))
        .agregarBloque(bFactory.createBloque("steel",9 , 12))
        .agregarBloque(bFactory.createBloque("steel",9 , 13))
        .agregarBloque(bFactory.createBloque("brick",9  , 14))      
        .agregarBloque(bFactory.createBloque("brick",9  , 15))
        .agregarBloque(bFactory.createBloque("brick",9 , 16))
        .agregarBloque(bFactory.createBloque("brick",9  , 17))
        .agregarBloque(bFactory.createBloque("grass",9 ,18 ))
        .agregarBloque(bFactory.createBloque("grass",9 , 19))
        .agregarBloque(bFactory.createBloque("grass",9, 20))
        .agregarBloque(bFactory.createBloque("grass",9 , 21))      
        .agregarBloque(bFactory.createBloque("steel",9  , 24))
        .agregarBloque(bFactory.createBloque("steel",9 , 25))
        
        .agregarBloque(bFactory.createBloque("brick", 10, 2))
	.agregarBloque(bFactory.createBloque("brick", 10, 3))
	.agregarBloque(bFactory.createBloque("brick",10 , 4))
	.agregarBloque(bFactory.createBloque("brick", 10, 5))
	.agregarBloque(bFactory.createBloque("brick", 10, 6))
	.agregarBloque(bFactory.createBloque("brick", 10, 7))
	.agregarBloque(bFactory.createBloque("steel", 10, 8))
	.agregarBloque(bFactory.createBloque("steel", 10, 9))  
        .agregarBloque(bFactory.createBloque("brick", 10, 14))
	.agregarBloque(bFactory.createBloque("brick", 10, 15)) 
        .agregarBloque(bFactory.createBloque("grass", 10, 18))
	.agregarBloque(bFactory.createBloque("grass", 10, 19))
	.agregarBloque(bFactory.createBloque("grass", 10, 20))
	.agregarBloque(bFactory.createBloque("grass", 10, 21))  
        .agregarBloque(bFactory.createBloque("brick", 10, 25))
                
        .agregarBloque(bFactory.createBloque("steel", 11, 8))
	.agregarBloque(bFactory.createBloque("steel", 11, 9))
	.agregarBloque(bFactory.createBloque("brick",11 , 14))
	.agregarBloque(bFactory.createBloque("brick", 11, 15))
	.agregarBloque(bFactory.createBloque("grass", 11, 18))
	.agregarBloque(bFactory.createBloque("grass", 11, 19))
	.agregarBloque(bFactory.createBloque("grass", 11, 20))
	.agregarBloque(bFactory.createBloque("grass", 11, 21))  
        .agregarBloque(bFactory.createBloque("brick", 11, 25))
        
        .agregarBloque(bFactory.createBloque("brick", 12, 1))        
        .agregarBloque(bFactory.createBloque("brick", 12, 2))
	.agregarBloque(bFactory.createBloque("brick",12, 3))
	.agregarBloque(bFactory.createBloque("brick",12 , 4))
	.agregarBloque(bFactory.createBloque("brick",12 , 5))
	.agregarBloque(bFactory.createBloque("brick",12 , 6))
	.agregarBloque(bFactory.createBloque("brick", 12, 7))
	.agregarBloque(bFactory.createBloque("steel",12 , 10))
	.agregarBloque(bFactory.createBloque("steel",12 , 11))
        .agregarBloque(bFactory.createBloque("grass",12 , 12))
        .agregarBloque(bFactory.createBloque("grass",12 , 13))
	.agregarBloque(bFactory.createBloque("grass",12 , 14)) 
        .agregarBloque(bFactory.createBloque("grass",12 , 15))
	.agregarBloque(bFactory.createBloque("grass",12 , 16))
        .agregarBloque(bFactory.createBloque("grass",12 , 17))
	.agregarBloque(bFactory.createBloque("grass",12 , 18)) 
        .agregarBloque(bFactory.createBloque("grass",12 , 19))
	.agregarBloque(bFactory.createBloque("grass",12 , 20))
        .agregarBloque(bFactory.createBloque("grass",12 , 21))
                
        .agregarBloque(bFactory.createBloque("brick", 13, 1))        
        .agregarBloque(bFactory.createBloque("brick", 13, 2))
	.agregarBloque(bFactory.createBloque("brick",13, 3))
	.agregarBloque(bFactory.createBloque("brick",13 , 4))
	.agregarBloque(bFactory.createBloque("brick",13 , 5))
	.agregarBloque(bFactory.createBloque("brick",13 , 6))
	.agregarBloque(bFactory.createBloque("brick", 13, 7))
	.agregarBloque(bFactory.createBloque("steel",13, 10))
	.agregarBloque(bFactory.createBloque("steel",13 , 11))
        .agregarBloque(bFactory.createBloque("grass",13 , 12))
        .agregarBloque(bFactory.createBloque("grass",13 , 13))
	.agregarBloque(bFactory.createBloque("grass",13 , 14)) 
        .agregarBloque(bFactory.createBloque("grass",13 , 15))
	.agregarBloque(bFactory.createBloque("grass",13 , 16))
        .agregarBloque(bFactory.createBloque("grass",13 , 17))
	.agregarBloque(bFactory.createBloque("grass",13 , 18)) 
        .agregarBloque(bFactory.createBloque("grass",13 , 19))
	.agregarBloque(bFactory.createBloque("grass",13 , 20))
        .agregarBloque(bFactory.createBloque("grass",13 , 21))
                
        .agregarBloque(bFactory.createBloque("steel", 14, 6))
	.agregarBloque(bFactory.createBloque("steel", 14, 7))
        .agregarBloque(bFactory.createBloque("grass",14 , 12))
        .agregarBloque(bFactory.createBloque("grass",14 , 13))
	.agregarBloque(bFactory.createBloque("grass",14 , 14)) 
        .agregarBloque(bFactory.createBloque("grass",14 , 15))
	.agregarBloque(bFactory.createBloque("grass",14 , 16))
        .agregarBloque(bFactory.createBloque("grass",14 , 17))
	.agregarBloque(bFactory.createBloque("grass",14 , 18)) 
        .agregarBloque(bFactory.createBloque("grass",14 , 19))
	.agregarBloque(bFactory.createBloque("grass",14 , 20))
        .agregarBloque(bFactory.createBloque("grass",14 , 21))
        .agregarBloque(bFactory.createBloque("brick",14 , 22))
        .agregarBloque(bFactory.createBloque("brick",14 , 23))
           
        .agregarBloque(bFactory.createBloque("steel", 15, 6))
	.agregarBloque(bFactory.createBloque("steel", 15, 7))
        .agregarBloque(bFactory.createBloque("grass",15 , 12))
        .agregarBloque(bFactory.createBloque("grass",15 , 13))
	.agregarBloque(bFactory.createBloque("grass",15 , 14)) 
        .agregarBloque(bFactory.createBloque("grass",15 , 15))
	.agregarBloque(bFactory.createBloque("grass",15 , 16))
        .agregarBloque(bFactory.createBloque("grass",15 , 17))
	.agregarBloque(bFactory.createBloque("grass",15 , 18)) 
        .agregarBloque(bFactory.createBloque("grass",15 , 19))
	.agregarBloque(bFactory.createBloque("grass",15 , 20))
        .agregarBloque(bFactory.createBloque("grass",15 , 21))
        .agregarBloque(bFactory.createBloque("brick",15 , 22))
        .agregarBloque(bFactory.createBloque("brick",15 , 23))   
        
                
        .agregarBloque(bFactory.createBloque("steel",16 , 0))
	.agregarBloque(bFactory.createBloque("steel", 16, 1))
	.agregarBloque(bFactory.createBloque("brick", 16, 2))
	.agregarBloque(bFactory.createBloque("brick", 16, 3))
	.agregarBloque(bFactory.createBloque("grass", 16, 6))
	.agregarBloque(bFactory.createBloque("grass", 16, 7))
	.agregarBloque(bFactory.createBloque("grass",16 , 8))
	.agregarBloque(bFactory.createBloque("grass",16 ,9))
        .agregarBloque(bFactory.createBloque("grass",16 , 10))
	.agregarBloque(bFactory.createBloque("grass",16 , 11))
	.agregarBloque(bFactory.createBloque("grass",16 , 12))
	.agregarBloque(bFactory.createBloque("grass",16 , 13))
        .agregarBloque(bFactory.createBloque("steel",16 , 14))
	.agregarBloque(bFactory.createBloque("steel", 16, 15))
        .agregarBloque(bFactory.createBloque("grass",16 , 16))
	.agregarBloque(bFactory.createBloque("grass",16 ,17))
        .agregarBloque(bFactory.createBloque("grass",16 , 18))
	.agregarBloque(bFactory.createBloque("grass",16 , 19))
	.agregarBloque(bFactory.createBloque("grass",16 , 20))
	.agregarBloque(bFactory.createBloque("grass",16 , 21))
        .agregarBloque(bFactory.createBloque("brick",16 , 22))
	.agregarBloque(bFactory.createBloque("brick",16 , 23))       
                
                
        .agregarBloque(bFactory.createBloque("steel",17 , 0))
	.agregarBloque(bFactory.createBloque("steel", 17, 1))
	.agregarBloque(bFactory.createBloque("brick", 17, 2))
	.agregarBloque(bFactory.createBloque("brick", 17, 3))
	.agregarBloque(bFactory.createBloque("grass", 17, 6))
	.agregarBloque(bFactory.createBloque("grass", 17, 7))
	.agregarBloque(bFactory.createBloque("grass",17 , 8))
	.agregarBloque(bFactory.createBloque("grass",17 ,9))
        .agregarBloque(bFactory.createBloque("grass",17 , 10))
	.agregarBloque(bFactory.createBloque("grass",17 , 11))
	.agregarBloque(bFactory.createBloque("grass",17 , 12))
	.agregarBloque(bFactory.createBloque("grass",17 , 13))
        .agregarBloque(bFactory.createBloque("steel",17 , 14))
	.agregarBloque(bFactory.createBloque("steel", 17, 15))
        .agregarBloque(bFactory.createBloque("grass",17 , 16))
	.agregarBloque(bFactory.createBloque("grass",17 ,17))
        .agregarBloque(bFactory.createBloque("grass",17 , 18))
	.agregarBloque(bFactory.createBloque("grass",17 , 19))
	.agregarBloque(bFactory.createBloque("grass",17 , 20))
	.agregarBloque(bFactory.createBloque("grass",17 , 21))
        .agregarBloque(bFactory.createBloque("brick",17 , 22))
	.agregarBloque(bFactory.createBloque("brick",17 , 23))
             
        .agregarBloque(bFactory.createBloque("brick",18 , 1))
	.agregarBloque(bFactory.createBloque("brick", 18, 2))
	.agregarBloque(bFactory.createBloque("brick", 18, 3))
	.agregarBloque(bFactory.createBloque("grass",18 , 4))
	.agregarBloque(bFactory.createBloque("grass",18 , 5))
	.agregarBloque(bFactory.createBloque("grass", 18, 6))
	.agregarBloque(bFactory.createBloque("grass", 18, 7))
	.agregarBloque(bFactory.createBloque("grass", 18, 8))
        .agregarBloque(bFactory.createBloque("grass",18 , 9))
	.agregarBloque(bFactory.createBloque("grass", 18, 10))
	.agregarBloque(bFactory.createBloque("grass", 18, 11))
	.agregarBloque(bFactory.createBloque("grass",18 , 12))
	.agregarBloque(bFactory.createBloque("grass",18 , 13))
	.agregarBloque(bFactory.createBloque("brick", 18, 22))
	.agregarBloque(bFactory.createBloque("brick", 18, 23))
	.agregarBloque(bFactory.createBloque("brick", 18,  24))
                
        .agregarBloque(bFactory.createBloque("brick",19 , 1))
	.agregarBloque(bFactory.createBloque("brick", 19, 2))
	.agregarBloque(bFactory.createBloque("brick", 19, 3))
	.agregarBloque(bFactory.createBloque("grass",19 , 4))
	.agregarBloque(bFactory.createBloque("grass",19 , 5))
	.agregarBloque(bFactory.createBloque("grass", 19, 6))
	.agregarBloque(bFactory.createBloque("grass", 19, 7))
	.agregarBloque(bFactory.createBloque("grass", 19, 8))
        .agregarBloque(bFactory.createBloque("grass",19 , 9))
	.agregarBloque(bFactory.createBloque("grass", 19, 10))
	.agregarBloque(bFactory.createBloque("grass", 19, 11))
	.agregarBloque(bFactory.createBloque("grass",19 , 12))
	.agregarBloque(bFactory.createBloque("grass",19, 13))
	.agregarBloque(bFactory.createBloque("brick", 19, 22))
	.agregarBloque(bFactory.createBloque("brick", 19, 23))
	.agregarBloque(bFactory.createBloque("brick", 19,  24))
                
        .agregarBloque(bFactory.createBloque("brick",20 , 2))
	.agregarBloque(bFactory.createBloque("brick", 20, 3))
	.agregarBloque(bFactory.createBloque("grass", 20, 4))
	.agregarBloque(bFactory.createBloque("grass",20 , 5))
	.agregarBloque(bFactory.createBloque("grass",20 , 6))
	.agregarBloque(bFactory.createBloque("grass", 20, 7))
	.agregarBloque(bFactory.createBloque("steel", 20, 16))
	.agregarBloque(bFactory.createBloque("steel", 20, 17))
        .agregarBloque(bFactory.createBloque("brick",20 , 18))
	.agregarBloque(bFactory.createBloque("brick", 20, 15))
        .agregarBloque(bFactory.createBloque("brick",20 , 19))
	.agregarBloque(bFactory.createBloque("brick", 20, 20))        
        .agregarBloque(bFactory.createBloque("brick",20 , 21))
	.agregarBloque(bFactory.createBloque("brick", 20, 22))
        .agregarBloque(bFactory.createBloque("brick", 20, 23))
                
        .agregarBloque(bFactory.createBloque("brick",21 , 2))
	.agregarBloque(bFactory.createBloque("brick", 21, 3))
	.agregarBloque(bFactory.createBloque("grass", 21, 4))
	.agregarBloque(bFactory.createBloque("grass",21 , 5))
	.agregarBloque(bFactory.createBloque("grass",21 , 6))
	.agregarBloque(bFactory.createBloque("grass", 21, 7))
        .agregarBloque(bFactory.createBloque("brick",21 , 18))
	.agregarBloque(bFactory.createBloque("brick", 21, 15))
        .agregarBloque(bFactory.createBloque("brick",21 , 19))
	.agregarBloque(bFactory.createBloque("brick", 21, 20))        
        .agregarBloque(bFactory.createBloque("brick",21 , 21))
	.agregarBloque(bFactory.createBloque("brick", 21, 22))
        .agregarBloque(bFactory.createBloque("brick", 21, 23))
                
        .agregarBloque(bFactory.createBloque("grass",22 , 4))
	.agregarBloque(bFactory.createBloque("grass", 22, 5))
	.agregarBloque(bFactory.createBloque("grass", 22, 6))
	.agregarBloque(bFactory.createBloque("grass",22 , 7))
	.agregarBloque(bFactory.createBloque("brick",22 , 18))
	.agregarBloque(bFactory.createBloque("brick", 22,19 ))
        .agregarBloque(bFactory.createBloque("brick", 22,23 ))        
                
                
	.agregarBloque(bFactory.createBloque("grass",23 , 4))
	.agregarBloque(bFactory.createBloque("grass", 23, 5))
	.agregarBloque(bFactory.createBloque("grass", 23, 6))
	.agregarBloque(bFactory.createBloque("grass",23 , 7))
        .agregarBloque(bFactory.createBloque("brick",23 , 11))
	.agregarBloque(bFactory.createBloque("brick", 23,12 ))
        .agregarBloque(bFactory.createBloque("brick", 23,13 ))
        .agregarBloque(bFactory.createBloque("brick", 23,14 ))
	.agregarBloque(bFactory.createBloque("brick",23 , 18))
	.agregarBloque(bFactory.createBloque("brick", 23,19 ))
        .agregarBloque(bFactory.createBloque("brick", 23,23 ))  
	
                
                
        .agregarBloque(bFactory.createBloque("grass", 24, 4))
	.agregarBloque(bFactory.createBloque("grass", 24,5))
        .agregarBloque(bFactory.createBloque("grass",24 , 6))
	.agregarBloque(bFactory.createBloque("grass", 24, 7))
        .agregarBloque(bFactory.createBloque("brick", 24, 11))
	.agregarBloque(bFactory.createBloque("brick", 24, 14))
                
        .agregarBloque(bFactory.createBloque("brick", 25, 2))
	.agregarBloque(bFactory.createBloque("brick", 25,3))
        .agregarBloque(bFactory.createBloque("grass",25 , 4))
	.agregarBloque(bFactory.createBloque("grass", 25, 5))
        .agregarBloque(bFactory.createBloque("grass", 25, 6))
	.agregarBloque(bFactory.createBloque("grass", 25, 7))
        .agregarBloque(bFactory.createBloque("brick",25 , 11))
	.agregarBloque(bFactory.createBloque("brick", 25, 14))
        .build();
        mapa3.imprimir();
        filemanager.FileManager.writeObject(mapa3, "Mapas\\mapa3.txt");
        
        Mapa mapa4 = new MapaBuilder()
        .agregarBloque(bFactory.createBloque("brick", 0, 8))
	.agregarBloque(bFactory.createBloque("brick", 0,9))
        .agregarBloque(bFactory.createBloque("brick",0 , 10))
	.agregarBloque(bFactory.createBloque("brick", 0,11))
                
        .agregarBloque(bFactory.createBloque("brick", 1, 8))
	.agregarBloque(bFactory.createBloque("brick", 1,9))
        .agregarBloque(bFactory.createBloque("brick",1, 10))
	.agregarBloque(bFactory.createBloque("brick", 1,11))
        
        .agregarBloque(bFactory.createBloque("brick", 2, 8))
	.agregarBloque(bFactory.createBloque("brick", 2,9))
        .agregarBloque(bFactory.createBloque("steel", 2, 16))
	.agregarBloque(bFactory.createBloque("steel", 2,17))
        .agregarBloque(bFactory.createBloque("steel", 2, 18))
	.agregarBloque(bFactory.createBloque("steel", 2,19))
        .agregarBloque(bFactory.createBloque("steel", 2, 20))
	.agregarBloque(bFactory.createBloque("steel", 2,21))
               
                
        .agregarBloque(bFactory.createBloque("steel", 3, 0))
	.agregarBloque(bFactory.createBloque("steel", 3, 1))
        .agregarBloque(bFactory.createBloque("brick", 3, 4))
	.agregarBloque(bFactory.createBloque("brick", 3, 5))
        .agregarBloque(bFactory.createBloque("brick", 3, 8))
	.agregarBloque(bFactory.createBloque("brick", 3, 9))
        .agregarBloque(bFactory.createBloque("steel", 3, 20))
	.agregarBloque(bFactory.createBloque("steel", 3,21))  
                
         
        .agregarBloque(bFactory.createBloque("steel", 4, 0))
	.agregarBloque(bFactory.createBloque("steel", 4, 1))
        .agregarBloque(bFactory.createBloque("brick", 4, 4))
	.agregarBloque(bFactory.createBloque("brick", 4, 5))
        .agregarBloque(bFactory.createBloque("brick", 4, 12))
	.agregarBloque(bFactory.createBloque("brick", 4, 13)) 
                
        .agregarBloque(bFactory.createBloque("steel", 5, 0))
	.agregarBloque(bFactory.createBloque("steel", 5, 1))
        .agregarBloque(bFactory.createBloque("brick", 5, 4))
	.agregarBloque(bFactory.createBloque("brick", 5, 5))
        .agregarBloque(bFactory.createBloque("brick", 5, 12))
	.agregarBloque(bFactory.createBloque("brick", 5, 13))         
                
        .agregarBloque(bFactory.createBloque("brick", 6, 0))
	.agregarBloque(bFactory.createBloque("brick", 6, 1))
        .agregarBloque(bFactory.createBloque("brick", 6, 4))
	.agregarBloque(bFactory.createBloque("brick", 6, 5))
        .agregarBloque(bFactory.createBloque("brick", 6, 6))
	.agregarBloque(bFactory.createBloque("brick", 6, 7)) 
        .agregarBloque(bFactory.createBloque("brick", 6, 8))
	.agregarBloque(bFactory.createBloque("brick", 6, 9))        
        .agregarBloque(bFactory.createBloque("brick", 6, 12))
	.agregarBloque(bFactory.createBloque("brick", 6, 13))        
        .agregarBloque(bFactory.createBloque("brick", 6, 14))
	.agregarBloque(bFactory.createBloque("brick", 6, 15))
        .agregarBloque(bFactory.createBloque("water", 6, 18))
	.agregarBloque(bFactory.createBloque("water", 6, 19)) 
        .agregarBloque(bFactory.createBloque("water", 6, 20))
	.agregarBloque(bFactory.createBloque("water", 6, 21))
        .agregarBloque(bFactory.createBloque("water", 6, 24))
	.agregarBloque(bFactory.createBloque("water", 6, 25)) 
                
        .agregarBloque(bFactory.createBloque("brick", 7, 0))
	.agregarBloque(bFactory.createBloque("brick", 7, 1))
        .agregarBloque(bFactory.createBloque("brick", 7, 4))
	.agregarBloque(bFactory.createBloque("brick", 7, 5))
        .agregarBloque(bFactory.createBloque("brick", 7, 6))
	.agregarBloque(bFactory.createBloque("brick", 7, 7)) 
        .agregarBloque(bFactory.createBloque("brick", 7, 8))
	.agregarBloque(bFactory.createBloque("brick", 7, 9))        
        .agregarBloque(bFactory.createBloque("brick", 7, 12))
	.agregarBloque(bFactory.createBloque("brick", 7, 13))        
        .agregarBloque(bFactory.createBloque("brick", 7, 14))
	.agregarBloque(bFactory.createBloque("brick", 7, 15))
        .agregarBloque(bFactory.createBloque("water", 7, 18))
	.agregarBloque(bFactory.createBloque("water", 7, 19)) 
        .agregarBloque(bFactory.createBloque("water", 7, 20))
	.agregarBloque(bFactory.createBloque("water", 7, 21))
        .agregarBloque(bFactory.createBloque("water", 7, 24))
	.agregarBloque(bFactory.createBloque("water", 7, 25))         
                
        .agregarBloque(bFactory.createBloque("brick", 8, 0))
	.agregarBloque(bFactory.createBloque("brick", 8, 1))
        .agregarBloque(bFactory.createBloque("brick", 8, 8))
	.agregarBloque(bFactory.createBloque("brick", 8, 9))
        .agregarBloque(bFactory.createBloque("water", 8, 18))
	.agregarBloque(bFactory.createBloque("water", 8, 19))        
                
        .agregarBloque(bFactory.createBloque("water", 9, 18))
	.agregarBloque(bFactory.createBloque("water", 9, 19))         
                
        
        .agregarBloque(bFactory.createBloque("water", 10, 8))
	.agregarBloque(bFactory.createBloque("water", 10, 9))
        .agregarBloque(bFactory.createBloque("water", 10, 10))
	.agregarBloque(bFactory.createBloque("water", 10, 11))
        .agregarBloque(bFactory.createBloque("water", 10, 14))
	.agregarBloque(bFactory.createBloque("water", 10, 15))
        .agregarBloque(bFactory.createBloque("water", 10, 16))
	.agregarBloque(bFactory.createBloque("water", 10, 17))
        .agregarBloque(bFactory.createBloque("water", 10, 18))
	.agregarBloque(bFactory.createBloque("water", 10, 19)) 
        .agregarBloque(bFactory.createBloque("brick", 10, 22))
	.agregarBloque(bFactory.createBloque("brick", 10, 23))
        .agregarBloque(bFactory.createBloque("brick", 10, 24))
	.agregarBloque(bFactory.createBloque("brick", 10, 25)) 
        
        .agregarBloque(bFactory.createBloque("brick", 11, 4))
	.agregarBloque(bFactory.createBloque("brick", 11, 5))
        .agregarBloque(bFactory.createBloque("water", 11, 8))
	.agregarBloque(bFactory.createBloque("water", 11, 9))
        .agregarBloque(bFactory.createBloque("water", 11, 10))
	.agregarBloque(bFactory.createBloque("water", 11, 11))
        .agregarBloque(bFactory.createBloque("water", 11, 14))
	.agregarBloque(bFactory.createBloque("water", 11, 15))
        .agregarBloque(bFactory.createBloque("water", 11, 16))
	.agregarBloque(bFactory.createBloque("water", 11, 17))
        .agregarBloque(bFactory.createBloque("water", 11, 18))
	.agregarBloque(bFactory.createBloque("water", 11, 19)) 
        .agregarBloque(bFactory.createBloque("brick", 11, 22))
	.agregarBloque(bFactory.createBloque("brick", 11, 23))
        .agregarBloque(bFactory.createBloque("brick", 11, 24))
	.agregarBloque(bFactory.createBloque("brick", 11, 25)) 
                
        .agregarBloque(bFactory.createBloque("brick", 12, 0))
	.agregarBloque(bFactory.createBloque("brick", 12, 1))
        .agregarBloque(bFactory.createBloque("brick", 12, 2))
	.agregarBloque(bFactory.createBloque("brick", 12, 3))
        .agregarBloque(bFactory.createBloque("water", 12, 8))
	.agregarBloque(bFactory.createBloque("water", 12, 9))
        .agregarBloque(bFactory.createBloque("brick", 12, 10))
	.agregarBloque(bFactory.createBloque("brick", 12, 11))
        .agregarBloque(bFactory.createBloque("brick", 12, 14))
	.agregarBloque(bFactory.createBloque("brick", 12, 15))
        .agregarBloque(bFactory.createBloque("brick", 12, 16))
                
         
        .agregarBloque(bFactory.createBloque("brick", 13, 0))
	.agregarBloque(bFactory.createBloque("brick", 13, 1))
        .agregarBloque(bFactory.createBloque("brick", 13, 2))
	.agregarBloque(bFactory.createBloque("brick", 13, 3))
        .agregarBloque(bFactory.createBloque("water", 13, 8))
	.agregarBloque(bFactory.createBloque("water", 13, 9))
        .agregarBloque(bFactory.createBloque("brick", 13, 10))
	.agregarBloque(bFactory.createBloque("brick", 13, 11))
        .agregarBloque(bFactory.createBloque("brick", 13, 14))
	.agregarBloque(bFactory.createBloque("brick", 13, 15))
        .agregarBloque(bFactory.createBloque("brick", 13, 16))        
                
        
        .agregarBloque(bFactory.createBloque("water", 14, 8))
	.agregarBloque(bFactory.createBloque("water", 14, 9))
	.agregarBloque(bFactory.createBloque("steel", 14, 21))
        .agregarBloque(bFactory.createBloque("steel", 14, 22))  
                
        .agregarBloque(bFactory.createBloque("water", 15, 8))
	.agregarBloque(bFactory.createBloque("water", 15, 9))
	.agregarBloque(bFactory.createBloque("steel", 15, 21))
        .agregarBloque(bFactory.createBloque("steel", 15, 22))
                
        .agregarBloque(bFactory.createBloque("water", 16, 0))
	.agregarBloque(bFactory.createBloque("water", 16, 1))
	.agregarBloque(bFactory.createBloque("water", 16, 2))
        .agregarBloque(bFactory.createBloque("water", 16, 3))
        .agregarBloque(bFactory.createBloque("water", 16, 4))
        .agregarBloque(bFactory.createBloque("water", 16, 5))
        .agregarBloque(bFactory.createBloque("water", 16, 8))
	.agregarBloque(bFactory.createBloque("water", 16, 9))
        .agregarBloque(bFactory.createBloque("steel", 16, 12)) 
        .agregarBloque(bFactory.createBloque("steel", 16, 13)) 
        .agregarBloque(bFactory.createBloque("brick", 16, 16)) 
        .agregarBloque(bFactory.createBloque("brick", 16, 17)) 
	.agregarBloque(bFactory.createBloque("steel", 16, 21))        
                
        .agregarBloque(bFactory.createBloque("water", 17, 0))
	.agregarBloque(bFactory.createBloque("water", 17, 1))
	.agregarBloque(bFactory.createBloque("water", 17, 2))
        .agregarBloque(bFactory.createBloque("water", 17, 3))
        .agregarBloque(bFactory.createBloque("water", 17, 4))
        .agregarBloque(bFactory.createBloque("water", 17, 5))
        .agregarBloque(bFactory.createBloque("water", 17, 8))
	.agregarBloque(bFactory.createBloque("water", 17, 9))
        .agregarBloque(bFactory.createBloque("steel", 17, 12)) 
        .agregarBloque(bFactory.createBloque("steel", 17, 13)) 
        .agregarBloque(bFactory.createBloque("brick", 17, 16)) 
        .agregarBloque(bFactory.createBloque("brick", 17, 17)) 
	.agregarBloque(bFactory.createBloque("steel", 17, 21))          
            
        .agregarBloque(bFactory.createBloque("steel", 18, 21)) 
        .agregarBloque(bFactory.createBloque("brick", 18, 22))         
        .agregarBloque(bFactory.createBloque("brick", 18, 23))           
        .agregarBloque(bFactory.createBloque("brick", 18, 24))           
        .agregarBloque(bFactory.createBloque("brick", 18, 25))          
                
        .agregarBloque(bFactory.createBloque("brick", 19, 6))
	.agregarBloque(bFactory.createBloque("brick", 19, 7))
	.agregarBloque(bFactory.createBloque("brick", 19, 8))
        .agregarBloque(bFactory.createBloque("brick", 19, 9))
	.agregarBloque(bFactory.createBloque("steel", 19, 21)) 
        .agregarBloque(bFactory.createBloque("brick", 19, 22))         
        .agregarBloque(bFactory.createBloque("brick", 19, 23))           
        .agregarBloque(bFactory.createBloque("brick", 19, 24))           
        .agregarBloque(bFactory.createBloque("brick", 19, 25)) 
                
        .agregarBloque(bFactory.createBloque("brick", 20, 8))
	.agregarBloque(bFactory.createBloque("brick", 20, 9))
	.agregarBloque(bFactory.createBloque("brick", 20, 10))
        .agregarBloque(bFactory.createBloque("brick", 20, 11))
        .agregarBloque(bFactory.createBloque("brick", 20, 12))
	.agregarBloque(bFactory.createBloque("brick", 20, 13))
	.agregarBloque(bFactory.createBloque("brick", 20, 14))
        .agregarBloque(bFactory.createBloque("brick", 20, 15))
	.agregarBloque(bFactory.createBloque("brick", 20, 16)) 
        .agregarBloque(bFactory.createBloque("brick", 20, 17))        
                
        .agregarBloque(bFactory.createBloque("brick", 21, 8))
	.agregarBloque(bFactory.createBloque("brick", 21, 9))
	.agregarBloque(bFactory.createBloque("brick", 21, 16)) 
        .agregarBloque(bFactory.createBloque("brick", 21, 17))         
        .agregarBloque(bFactory.createBloque("brick", 21, 18)) 
        .agregarBloque(bFactory.createBloque("brick", 21, 19))     
                
        .agregarBloque(bFactory.createBloque("brick", 22, 0))
	.agregarBloque(bFactory.createBloque("brick", 22, 1))
	.agregarBloque(bFactory.createBloque("brick", 22, 2)) 
        .agregarBloque(bFactory.createBloque("brick", 22, 3))         
        .agregarBloque(bFactory.createBloque("brick", 22, 4)) 
        .agregarBloque(bFactory.createBloque("brick", 22, 5))         
        .agregarBloque(bFactory.createBloque("brick", 22, 18)) 
        .agregarBloque(bFactory.createBloque("brick", 22, 19))         
        .agregarBloque(bFactory.createBloque("brick", 22, 20)) 
        .agregarBloque(bFactory.createBloque("brick", 22, 21))    
                
        .agregarBloque(bFactory.createBloque("brick", 23, 0))
	.agregarBloque(bFactory.createBloque("brick", 23, 1))
	.agregarBloque(bFactory.createBloque("brick", 23, 2)) 
        .agregarBloque(bFactory.createBloque("brick", 23, 3)) 
        .agregarBloque(bFactory.createBloque("brick", 23, 11)) 
        .agregarBloque(bFactory.createBloque("brick", 23, 12))
        .agregarBloque(bFactory.createBloque("brick", 23, 13)) 
        .agregarBloque(bFactory.createBloque("brick", 23, 14))
        .agregarBloque(bFactory.createBloque("brick", 23, 20)) 
        .agregarBloque(bFactory.createBloque("brick", 23, 21))         
           
                
        .agregarBloque(bFactory.createBloque("brick", 24, 0))
	.agregarBloque(bFactory.createBloque("brick", 24, 1))
        .agregarBloque(bFactory.createBloque("brick", 24, 11)) 
        .agregarBloque(bFactory.createBloque("brick", 24, 14))
                
        .agregarBloque(bFactory.createBloque("brick", 25, 11)) 
        .agregarBloque(bFactory.createBloque("brick", 25, 14))    
                
        .build();
        mapa4.imprimir();
        filemanager.FileManager.writeObject(mapa4, "Mapas\\mapa4.txt");
        
        // </editor-fold>
       
    
    }
    
}
